# Generated by Django 4.0.2 on 2022-03-29 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeTitle', models.CharField(max_length=200)),
                ('recipeText', models.TextField()),
                ('image', models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='recipeImages')),
                ('time_to_make', models.IntegerField(default=60)),
                ('difficulty', models.CharField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='IN', max_length=2)),
                ('parentRecipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenRecipe', to='home.recipe')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('asset_url', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='stepImages')),
                ('recipe', models.ManyToManyField(to='home.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipe', models.ManyToManyField(to='home.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('units', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('qualifier', models.CharField(blank=True, max_length=200, null=True)),
                ('recipe', models.ManyToManyField(to='home.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipe', models.ManyToManyField(to='home.Recipe')),
            ],
        ),
    ]
