# Generated by Django 4.0.2 on 2022-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(null=True, upload_to='recipeImages'),
        ),
    ]
