# Generated by Django 4.0.2 on 2022-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.FileField(null=True, upload_to='stepImages'),
        ),
    ]
