# Generated by Django 4.0.2 on 2022-03-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_recipe_recipeingredeients_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='qualifier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_to_make',
            field=models.IntegerField(default=60),
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ManyToManyField(to='home.Recipe'),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('qualifier', models.CharField(blank=True, max_length=200)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.recipe')),
            ],
        ),
    ]
