# Generated by Django 4.0.3 on 2022-04-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='image',
        ),
    ]
