# Generated by Django 4.0.2 on 2022-03-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ingredients_qualifier_recipe_time_to_make_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
    ]
