# Generated by Django 4.0.3 on 2022-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.FileField(null=True, upload_to='stepImages'),
        ),
    ]
