# Generated by Django 4.0.3 on 2022-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.FileField(upload_to='stepImages'),
        ),
    ]
