# Generated by Django 4.0.2 on 2022-03-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_ingredient_recipe_remove_step_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='qualifier',
        ),
        migrations.RemoveField(
            model_name='step',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='step',
            name='units',
        ),
        migrations.AddField(
            model_name='step',
            name='asset_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
