# Generated by Django 4.0.3 on 2022-04-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_step_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='image',
        ),
    ]
