# Generated by Django 4.0.2 on 2022-03-23 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_remove_step_qualifier_remove_step_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='name',
        ),
        migrations.AddField(
            model_name='step',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
