# Generated by Django 4.0.3 on 2022-04-09 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='stepImages'),
            preserve_default=False,
        ),
    ]
