# Generated by Django 4.0.2 on 2022-03-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_ingredient_quantity_alter_ingredient_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine_type',
            field=models.ManyToManyField(to='home.Cuisine_Type'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.ManyToManyField(to='home.Meal_Type'),
        ),
    ]
