# Generated by Django 4.0.2 on 2022-04-24 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_alter_recipe_likes_recipecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date posted'),
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentWriter', to=settings.AUTH_USER_MODEL),
        ),
    ]
