# Generated by Django 4.0.2 on 2022-03-23 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cuisine_type_meal_type_recipe_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='parentRecipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenRecipe', to='home.recipe'),
        ),
    ]
