# Generated by Django 4.0.2 on 2022-03-23 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_alter_ingredient_qualifier_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='writer',
        ),
        migrations.AddField(
            model_name='recipe',
            name='writer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
