# Generated by Django 4.0.2 on 2022-04-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_fix_recipecomment_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date posted'),
        ),
    ]
