# Generated by Django 4.0.2 on 2022-04-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_recipecomment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecomment',
            name='date',
        ),
    ]
