# Generated by Django 4.0.2 on 2022-04-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_recipecomment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeComment',
        ),
    ]
