# Generated by Django 4.0.2 on 2022-03-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_recipe_ease_of_prep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ease_of_prep',
            new_name='difficulty',
        ),
    ]
