# Generated by Django 4.0.2 on 2022-03-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_recipe_cuisine_type_remove_recipe_ingredients_and_more'),
    ]

    operations = [

    ]
