# Generated by Django 4.0.2 on 2022-05-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
