# Generated by Django 4.0.2 on 2022-03-31 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_favorite_like_option_alter_recipe_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('recipe_posted_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recipe')),
            ],
        ),
    ]
