# Generated by Django 4.0.2 on 2022-04-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='RecipeComment',
        ),
    ]
