# Generated by Django 4.0.2 on 2022-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_comment_recipecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecomment',
            name='recipe_posted_on',
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='recipe_posted_on',
            field=models.ManyToManyField(to='home.Recipe'),
        ),
    ]
