# Generated by Django 4.0.2 on 2022-04-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_recipecomment_recipe_posted_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecomment',
            old_name='recipe_posted_on',
            new_name='recipe',
        ),
    ]
